#!/bin/bash
# Quick Setup Check for MeLorAly Database

echo "========================================="
echo "MeLorAly Database Setup Checker"
echo "========================================="
echo ""

echo "Required Database Tables:"
echo "  ✓ profiles"
echo "  ✓ families"
echo "  ✓ family_members"
echo "  ✓ children"
echo "  ✓ messages"
echo "  ✓ notifications"
echo "  ✓ invitations"
echo "  ⚠ activity_completions (REQUIRED - check if exists)"
echo "  ⚠ contact_requests (REQUIRED - check if exists)"
echo ""

echo "Required Storage Buckets:"
echo "  ⚠ child-photos (REQUIRED - check if exists)"
echo ""

echo "========================================="
echo "ACTION ITEMS:"
echo "========================================="
echo ""
echo "1. DATABASE TABLES"
echo "   → Go to Supabase SQL Editor"
echo "   → Run: database/missing-tables.sql"
echo "   → This will create:"
echo "      - activity_completions table"
echo "      - contact_requests table"
echo ""

echo "2. STORAGE BUCKET"
echo "   → Go to Supabase Storage"
echo "   → Create new bucket: 'child-photos'"
echo "   → Set as PUBLIC bucket"
echo "   → Add RLS policies for family members"
echo ""

echo "3. VERIFY"
echo "   → Check Table Editor for all tables"
echo "   → Check Storage for child-photos bucket"
echo "   → Test /education route"
echo "   → Test contact form"
echo "   → Test photo upload"
echo ""

echo "========================================="
echo "QUICK LINKS:"
echo "========================================="
echo ""
echo "SQL File: MeLorAly/app/database/missing-tables.sql"
echo "Documentation: MISSING_TABLES_FIX.md"
echo ""

echo "Need help? Check the documentation for detailed instructions."
echo ""
